wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696185795.625479
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
metric:
  desc: null
  value: zhangs_metric
min_bundle_size:
  desc: null
  value: 1
min_confidence:
  desc: null
  value: 0.9
min_support:
  desc: null
  value: 0.05
min_threshold:
  desc: null
  value: 1.0
